### ISSUE TITLE
Permission for modifications

### ISSUE THREAD

**Issue by ankitrana1256** [redianmarku/Django-Twitter-Clone#19]
Sir, I am a python developer and your project seek my attention. I got some issues while setting up the environment and fulfilling the requirements but that was not the problem. However I think your project is awesome and need some modifications and addition of some new features. So, if you allow me I will use your resources and help in making V2. Thankyou

**Comment by redianmarku** [comment]
Yes, you can work on it and make it even better, you can send me pull request and I will approve.
