### ISSUE TITLE
Issue in running "pip install -r requirements.txt" command

### ISSUE THREAD

**Issue by GreenerGolden** [redianmarku/Django-Twitter-Clone#8]
After following the program as it is and running the "pip install -r requirements.txt" command, receiving the following error:-

-----------------------------------------------------------------------------------------------------------------------------------------
ERROR: Command errored out with exit status 1:
   command: 'c:\users\user\appdata\local\programs\python\python39\env\scripts\python.exe' 'c:\users\user\appdata\local\programs\python\python39\env\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\USER\AppData\Local\Temp\pip-build-env-4mvergx_\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet >= 0.4.17 ; platform_python_implementation == '"'"'CPython'"'"''
       cwd: None
  Complete output (29 lines):
  Collecting setuptools>=40.8.0
    Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
  Collecting wheel
    Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Collecting Cython>=3.0a5
    Using cached Cython-3.0a6-py2.py3-none-any.whl (1.0 MB)
  Collecting cffi>=1.12.3
    Using cached cffi-1.14.3-cp39-cp39-win_amd64.whl (179 kB)
  Collecting greenlet>=0.4.17
    Using cached greenlet-0.4.17.tar.gz (61 kB)
  Collecting pycparser
    Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
  Using legacy 'setup.py install' for greenlet, since package 'wheel' is not installed.
  Installing collected packages: setuptools, wheel, Cython, pycparser, cffi, greenlet
      Running setup.py install for greenlet: started
      Running setup.py install for greenlet: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\user\appdata\local\programs\python\python39\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-pjq47p2m\\greenlet\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-pjq47p2m\\greenlet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USER\AppData\Local\Temp\pip-record-gg91v1sz\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\USER\AppData\Local\Temp\pip-build-env-4mvergx_\overlay' --compile --install-headers 'C:\Users\USER\AppData\Local\Temp\pip-build-env-4mvergx_\overlay\include\site\python3.9\greenlet'
           cwd: C:\Users\USER\AppData\Local\Temp\pip-install-pjq47p2m\greenlet\
      Complete output (5 lines):
      running install
      running build
      running build_ext
      building 'greenlet' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'c:\users\user\appdata\local\programs\python\python39\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-pjq47p2m\\greenlet\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-pjq47p2m\\greenlet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USER\AppData\Local\Temp\pip-record-gg91v1sz\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\USER\AppData\Local\Temp\pip-build-env-4mvergx_\overlay' --compile --install-headers 'C:\Users\USER\AppData\Local\Temp\pip-build-env-4mvergx_\overlay\include\site\python3.9\greenlet' Check the logs for full command output.
  WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
  You should consider upgrading via the 'c:\users\user\appdata\local\programs\python\python39\env\scripts\python.exe -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\user\appdata\local\programs\python\python39\env\scripts\python.exe' 'c:\users\user\appdata\local\programs\python\python39\env\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\USER\AppData\Local\Temp\pip-build-env-4mvergx_\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet >= 0.4.17 ; platform_python_implementation == '"'"'CPython'"'"'' Check the logs for full command output.
----------------------------------------------------------------------------------------------------------------------------------------
Please help me how to resolve this issue. I haven't changed anything in any of the files and was following the instructions as given. This is urgent and a quick response back with the solution is really appreciated.

**Comment by redianmarku** [comment]
This is happening because your are using the latest version of python, I recommend you to use python 3.7 or 3.8 because python 3.9 isn’t stable and does not support all modules needed in this project.
